# Generated by Django 4.2.4 on 2023-09-16 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('preparacao', models.TextField(verbose_name='Preparação')),
                ('tempo_preparacao', models.IntegerField(verbose_name='Tempo de preparação')),
                ('tempo_tipo', models.CharField(max_length=20, verbose_name='Tipo de tempo')),
                ('porcao', models.IntegerField(verbose_name='Porções')),
                ('porcao_tipo', models.CharField(max_length=20, verbose_name='Tipo de tempo')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
                ('imagem', models.ImageField(upload_to='receitas/imagem/%Y/%m/%d/', verbose_name='Imagem')),
                ('publicado', models.BooleanField(default=True, verbose_name='Públicado ?')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receitas.categoria')),
            ],
        ),
    ]
