# Generated by Django 4.2.4 on 2023-08-31 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('descricao', models.CharField(max_length=160, verbose_name='Descrição')),
                ('tempo_preparacao', models.IntegerField(verbose_name='Tempo de preparação')),
                ('tempo_preparacao_unidade', models.CharField(max_length=65, verbose_name='Tempo preparação unidade')),
                ('porcoes', models.IntegerField(verbose_name='Porções')),
                ('porcoes_unidade', models.CharField(max_length=65, verbose_name='Porções Unidade')),
                ('preparacao', models.TextField(verbose_name='Preparação')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
                ('is_publicado', models.BooleanField(default=False, verbose_name='Públicado ?')),
                ('imagem', models.ImageField(upload_to='receitas/imageens/%Y/%m/%d/')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receitas.categoria')),
            ],
        ),
    ]
