# Generated by Django 4.2.4 on 2023-08-31 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_alter_categoria_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receita',
            options={'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
    ]
