# Generated by Django 4.2.4 on 2023-09-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_alter_receita_porcao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Públicado ?'),
        ),
    ]
