# Generated by Django 4.2.4 on 2023-09-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    operations = [
        migrations.AddField(
            model_name='receita',
            name='preparacao_is_html',
            field=models.BooleanField(default=False, verbose_name='Preparação is hmtl'),
        ),
    ]
